---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: lxd
lint:
  name: yamllint
  options:
    config-data:
      extends: default
      ignore: .venv_ansible*
      rules:
        line-length:
          max: 159
        truthy: disable
platforms:
  - name: molecule-newrelic-agent-php-test-xenial
    image: "ubuntu/xenial/amd64"
  - name: molecule-newrelic-agent-php-test-bionic
    image: "ubuntu/bionic/amd64"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH:
      $ephemeral_directory/:../roles/
  lint:
    name: ansible-lint
scenario:
  name: default-lxd
verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
